version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: 'gitlab-tools'
        container_name: app
        restart: always
        depends_on:
            - database
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/my-site
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - GITLAB_URL=${GITLAB_URL}
            - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
            - MYSQL_HOST=database
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_USER}

    database:
        image: mariadb
        container_name: db
        restart: always
        volumes:
            - gitlab-tools:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_USER}
      

volumes:
    gitlab-tools:
        driver: local
