version: '3'
services:
  database:
    image: mariadb
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file:
      - app/.env
    volumes:
      - $HOME/gitlab-tools/mysql/data:/var/lib/mysql
      
  app:
    image: 'gitlab-tools'
    links:
      - database
    depends_on:
      - database
    ports:
      - '80:80'
    volumes:
      - $HOME/gitlab-tools/.env:/var/www/my-site/.env
#      - $HOME/gitlab-tools/app:/var/www/my-site
